name: Test

on:
  push:
    branches: [main, release]
  pull_request:

jobs:
  static-check:
    name: Static check 🪲
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm run tsc

      - name: Typescript
        run: npm run tsc

      - name: Eslint
        run: npm run eslint

  build:
    name: Build 🏗
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm run tsc

      - name: Build
        run: npm run build
